In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Series

In [6]:
np.random.seed(42)
arr_int1 = np.random.randint(100, 10000, 100)
arr_int1.shape

(100,)

In [8]:
sr = pd.Series(arr_int1)
# sr

Seriesとndarry

In [9]:
type(sr)

pandas.core.series.Series

In [10]:
sr.ndim

1

In [12]:
sr.shape

(100,)

In [13]:
sr.max()

9792

Seriesに名前を付ける

In [14]:
sr.name = "Price"

In [17]:
sr_price = pd.Series(arr_int1, name="price")
sr_price

0     7370
1      960
2     5490
3     5291
4     5834
      ...
95     491
96    5992
97    3661
98    6284
99    3199
Name: price, Length: 100, dtype: int32

10-100の整数データ(size=100)からSeriesを作成

In [19]:
arr_int2 = np.random.randint(10, 100, 100)
sr_quantity = pd.Series(arr_int2, name="Quantity")

0-10の小数データ(100, 2)からDFを作成

In [24]:
arr_fl = np.random.rand(100, 2) * 10
# print(arr_fl)

In [26]:
df = pd.DataFrame(arr_fl)
df

           0         1
0   0.370076  5.962699
1   2.300088  1.205669
2   0.769532  6.962888
3   3.398750  7.247668
4   0.653563  3.152903
..       ...       ...
95  9.508636  1.510579
96  4.323348  9.436159
97  4.197273  6.385259
98  3.975944  2.742152
99  9.839776  4.093340

[100 rows x 2 columns]

In [29]:
df_wh = pd.DataFrame(arr_fl, columns=["Width", "Height"])
df_wh

       Width    Height
0   0.370076  5.962699
1   2.300088  1.205669
2   0.769532  6.962888
3   3.398750  7.247668
4   0.653563  3.152903
..       ...       ...
95  9.508636  1.510579
96  4.323348  9.436159
97  4.197273  6.385259
98  3.975944  2.742152
99  9.839776  4.093340

[100 rows x 2 columns]

40-60の範囲の一様分布の少数データ(100, 1)からDFを作成

In [35]:
arr_uni = np.random.uniform(40, 60, 100)
df_quality = pd.DataFrame(arr_uni, columns=["Quality"])
df_quality

      Quality
0   46.125072
1   52.477917
2   50.540829
3   48.521668
4   42.614208
..        ...
95  50.606043
96  40.839024
97  59.369776
98  55.974284
99  45.856441

[100 rows x 1 columns]

NormDist(mean=0, std=1)に従う小数データ(100, 1)からDFを作成

In [38]:
arr_norm = np.random.normal(loc=0, scale=1, size=(100, 1))
df_difference = pd.DataFrame(arr_norm, columns=["Difference"])
df_difference

    Difference
0     0.298753
1    -0.751791
2    -0.426358
3     1.148446
4     0.113270
..         ...
95   -0.120381
96   -2.172670
97    0.847422
98   -0.535328
99   -0.090533

[100 rows x 1 columns]

['red', 'green', 'blue'](100, 1), ['circle', 'square', 'triangle'](100, 1), ndarryを結合しDataFrameを作成

In [52]:
colors = ['red', 'green', 'blue']
shapes = ['circle', 'square', 'triangle']

arr_colors = np.random.choice(colors, size=(100, 1))
arr_shapes = np.random.choice(shapes, size=(100, 1))

arr_cs = np.concatenate([arr_colors, arr_shapes], axis=1)
arr_cs_hstack = np.hstack([arr_colors, arr_shapes])
arr_cs_vstack = np.vstack([arr_colors, arr_shapes])

In [54]:
df_cs = pd.DataFrame(arr_cs, columns=["Colors", "Shape"])
df_cs

   Colors     Shape
0    blue  triangle
1    blue    square
2     red    circle
3     red    square
4    blue    circle
..    ...       ...
95  green    square
96    red    circle
97   blue    square
98   blue    circle
99  green  triangle

[100 rows x 2 columns]

datetime 1977/7/5から1日刻み(100, 1)からDatetimeIndex, Seriesを作成

In [63]:
dates = pd.date_range('1997/7/5', periods=100, freq="D")
sr_date = pd.Series(dates, name="Date")
sr_date

0    1997-07-05
1    1997-07-06
2    1997-07-07
3    1997-07-08
4    1997-07-09
        ...
95   1997-10-08
96   1997-10-09
97   1997-10-10
98   1997-10-11
99   1997-10-12
Name: Date, Length: 100, dtype: datetime64[ns]

Series, DataFrameを結合

In [71]:
df = pd.concat([sr_date, sr_price, sr_quantity, df_wh, df_quality, df_difference], axis=1)

In [73]:
df.sample(3)

         Date  price  Quantity     Width    Height    Quality  Difference
66 1997-09-09   7729        98  3.351189  7.435083  54.326468   -0.903702
0  1997-07-05   7370        41  0.370076  5.962699  46.125072    0.298753
33 1997-08-07   7834        20  2.204862  1.864383  49.764823    2.589564

Series, DataFrameをndarryに変換

In [76]:
df.price.values

array([7370,  960, 5490, 5291, 5834, 6365,  566, 4526, 5678, 8422, 1785,
        869, 7049, 2533, 5411, 5151, 6520, 1284, 4655, 3485, 6496, 8766,
       9374, 2658, 7949, 2147, 2847, 9267,  289, 2834, 3105, 4758, 1999,
       7834, 1367, 1628, 3656, 3990, 8938, 5493, 8892, 8533, 7613, 2712,
       7141, 9655, 6335, 5586, 7199, 9770,  875, 8326, 3252, 1685, 4043,
       7655, 3173, 1121, 3943, 8089, 9792, 6973, 5775,  261, 4397, 1095,
       7729, 9567, 1116, 7969, 6539, 7992, 6963, 8016, 8629,  978, 9368,
       4987, 4959, 6431, 8671, 8784, 7308, 5376, 2162,  164, 8106, 2668,
       5563, 2127, 2795, 9787, 5358, 5718, 6836,  491, 5992, 3661, 6284,
       3199])

Series, DataFrameをndarryに変換

In [82]:
df.to_dict()

{'Date': {0: Timestamp('1997-07-05 00:00:00'),
  1: Timestamp('1997-07-06 00:00:00'),
  2: Timestamp('1997-07-07 00:00:00'),
  3: Timestamp('1997-07-08 00:00:00'),
  4: Timestamp('1997-07-09 00:00:00'),
  5: Timestamp('1997-07-10 00:00:00'),
  6: Timestamp('1997-07-11 00:00:00'),
  7: Timestamp('1997-07-12 00:00:00'),
  8: Timestamp('1997-07-13 00:00:00'),
  9: Timestamp('1997-07-14 00:00:00'),
  10: Timestamp('1997-07-15 00:00:00'),
  11: Timestamp('1997-07-16 00:00:00'),
  12: Timestamp('1997-07-17 00:00:00'),
  13: Timestamp('1997-07-18 00:00:00'),
  14: Timestamp('1997-07-19 00:00:00'),
  15: Timestamp('1997-07-20 00:00:00'),
  16: Timestamp('1997-07-21 00:00:00'),
  17: Timestamp('1997-07-22 00:00:00'),
  18: Timestamp('1997-07-23 00:00:00'),
  19: Timestamp('1997-07-24 00:00:00'),
  20: Timestamp('1997-07-25 00:00:00'),
  21: Timestamp('1997-07-26 00:00:00'),
  22: Timestamp('1997-07-27 00:00:00'),
  23: Timestamp('1997-07-28 00:00:00'),
  24: Timestamp('1997-07-29 00:00:00'),
  25: Timestamp('1997-07-30 00:00:00'),
  26: Timestamp('1997-07-31 00:00:00'),
  27: Timestamp('1997-08-01 00:00:00'),
  28: Timestamp('1997-08-02 00:00:00'),
  29: Timestamp('1997-08-03 00:00:00'),
  30: Timestamp('1997-08-04 00:00:00'),
  31: Timestamp('1997-08-05 00:00:00'),
  32: Timestamp('1997-08-06 00:00:00'),
  33: Timestamp('1997-08-07 00:00:00'),
  34: Timestamp('1997-08-08 00:00:00'),
  35: Timestamp('1997-08-09 00:00:00'),
  36: Timestamp('1997-08-10 00:00:00'),
  37: Timestamp('1997-08-11 00:00:00'),
  38: Timestamp('1997-08-12 00:00:00'),
  39: Timestamp('1997-08-13 00:00:00'),
  40: Timestamp('1997-08-14 00:00:00'),
  41: Timestamp('1997-08-15 00:00:00'),
  42: Timestamp('1997-08-16 00:00:00'),
  43: Timestamp('1997-08-17 00:00:00'),
  44: Timestamp('1997-08-18 00:00:00'),
  45: Timestamp('1997-08-19 00:00:00'),
  46: Timestamp('1997-08-20 00:00:00'),
  47: Timestamp('1997-08-21 00:00:00'),
  48: Timestamp('1997-08-22 00:00:00'),
  49: Timestamp('1997-08-23 00:00:00'),
  50: Timestamp('1997-08-24 00:00:00'),
  51: Timestamp('1997-08-25 00:00:00'),
  52: Timestamp('1997-08-26 00:00:00'),
  53: Timestamp('1997-08-27 00:00:00'),
  54: Timestamp('1997-08-28 00:00:00'),
  55: Timestamp('1997-08-29 00:00:00'),
  56: Timestamp('1997-08-30 00:00:00'),
  57: Timestamp('1997-08-31 00:00:00'),
  58: Timestamp('1997-09-01 00:00:00'),
  59: Timestamp('1997-09-02 00:00:00'),
  60: Timestamp('1997-09-03 00:00:00'),
  61: Timestamp('1997-09-04 00:00:00'),
  62: Timestamp('1997-09-05 00:00:00'),
  63: Timestamp('1997-09-06 00:00:00'),
  64: Timestamp('1997-09-07 00:00:00'),
  65: Timestamp('1997-09-08 00:00:00'),
  66: Timestamp('1997-09-09 00:00:00'),
  67: Timestamp('1997-09-10 00:00:00'),
  68: Timestamp('1997-09-11 00:00:00'),
  69: Timestamp('1997-09-12 00:00:00'),
  70: Timestamp('1997-09-13 00:00:00'),
  71: Timestamp('1997-09-14 00:00:00'),
  72: Timestamp('1997-09-15 00:00:00'),
  73: Timestamp('1997-09-16 00:00:00'),
  74: Timestamp('1997-09-17 00:00:00'),
  75: Timestamp('1997-09-18 00:00:00'),
  76: Timestamp('1997-09-19 00:00:00'),
  77: Timestamp('1997-09-20 00:00:00'),
  78: Timestamp('1997-09-21 00:00:00'),
  79: Timestamp('1997-09-22 00:00:00'),
  80: Timestamp('1997-09-23 00:00:00'),
  81: Timestamp('1997-09-24 00:00:00'),
  82: Timestamp('1997-09-25 00:00:00'),
  83: Timestamp('1997-09-26 00:00:00'),
  84: Timestamp('1997-09-27 00:00:00'),
  85: Timestamp('1997-09-28 00:00:00'),
  86: Timestamp('1997-09-29 00:00:00'),
  87: Timestamp('1997-09-30 00:00:00'),
  88: Timestamp('1997-10-01 00:00:00'),
  89: Timestamp('1997-10-02 00:00:00'),
  90: Timestamp('1997-10-03 00:00:00'),
  91: Timestamp('1997-10-04 00:00:00'),
  92: Timestamp('1997-10-05 00:00:00'),
  93: Timestamp('1997-10-06 00:00:00'),
  94: Timestamp('1997-10-07 00:00:00'),
  95: Timestamp('1997-10-08 00:00:00'),
  96: Timestamp('1997-10-09 00:00:00'),
  97: Timestamp('1997-10-10 00:00:00'),
  98: Timestamp('1997-10-11 00:00:00'),
  99: Timestamp('1997-10-12 00:00:00')},
 'price': {0: 7370,
  1: 960,
  2: 5490,
  3: 5291,
  4: 5834,
  5: 6365,
  6: 566,
  7: 4526,
  8: 5678,
  9: 8422,
  10: 1785,
  11: 869,
  12: 7049,
  13: 2533,
  14: 5411,
  15: 5151,
  16: 6520,
  17: 1284,
  18: 4655,
  19: 3485,
  20: 6496,
  21: 8766,
  22: 9374,
  23: 2658,
  24: 7949,
  25: 2147,
  26: 2847,
  27: 9267,
  28: 289,
  29: 2834,
  30: 3105,
  31: 4758,
  32: 1999,
  33: 7834,
  34: 1367,
  35: 1628,
  36: 3656,
  37: 3990,
  38: 8938,
  39: 5493,
  40: 8892,
  41: 8533,
  42: 7613,
  43: 2712,
  44: 7141,
  45: 9655,
  46: 6335,
  47: 5586,
  48: 7199,
  49: 9770,
  50: 875,
  51: 8326,
  52: 3252,
  53: 1685,
  54: 4043,
  55: 7655,
  56: 3173,
  57: 1121,
  58: 3943,
  59: 8089,
  60: 9792,
  61: 6973,
  62: 5775,
  63: 261,
  64: 4397,
  65: 1095,
  66: 7729,
  67: 9567,
  68: 1116,
  69: 7969,
  70: 6539,
  71: 7992,
  72: 6963,
  73: 8016,
  74: 8629,
  75: 978,
  76: 9368,
  77: 4987,
  78: 4959,
  79: 6431,
  80: 8671,
  81: 8784,
  82: 7308,
  83: 5376,
  84: 2162,
  85: 164,
  86: 8106,
  87: 2668,
  88: 5563,
  89: 2127,
  90: 2795,
  91: 9787,
  92: 5358,
  93: 5718,
  94: 6836,
  95: 491,
  96: 5992,
  97: 3661,
  98: 6284,
  99: 3199},
 'Quantity': {0: 41,
  1: 77,
  2: 64,
  3: 84,
  4: 65,
  5: 26,
  6: 47,
  7: 33,
  8: 78,
  9: 79,
  10: 95,
  11: 20,
  12: 25,
  13: 82,
  14: 68,
  15: 79,
  16: 89,
  17: 12,
  18: 29,
  19: 68,
  20: 45,
  21: 28,
  22: 99,
  23: 76,
  24: 28,
  25: 29,
  26: 80,
  27: 61,
  28: 42,
  29: 49,
  30: 48,
  31: 91,
  32: 10,
  33: 20,
  34: 66,
  35: 98,
  36: 59,
  37: 32,
  38: 40,
  39: 51,
  40: 16,
  41: 25,
  42: 99,
  43: 69,
  44: 11,
  45: 10,
  46: 57,
  47: 21,
  48: 78,
  49: 46,
  50: 41,
  51: 18,
  52: 28,
  53: 57,
  54: 89,
  55: 12,
  56: 29,
  57: 33,
  58: 63,
  59: 42,
  60: 33,
  61: 84,
  62: 81,
  63: 45,
  64: 47,
  65: 93,
  66: 98,
  67: 34,
  68: 27,
  69: 91,
  70: 75,
  71: 63,
  72: 44,
  73: 89,
  74: 70,
  75: 50,
  76: 42,
  77: 77,
  78: 42,
  79: 23,
  80: 30,
  81: 57,
  82: 29,
  83: 17,
  84: 16,
  85: 76,
  86: 26,
  87: 42,
  88: 57,
  89: 85,
  90: 68,
  91: 95,
  92: 31,
  93: 39,
  94: 47,
  95: 60,
  96: 63,
  97: 17,
  98: 36,
  99: 36},
 'Width': {0: 0.3700763471549262,
  1: 2.3000883728770303,
  2: 0.7695320162920916,
  3: 3.3987496376806616,
  4: 0.6535634079894237,
  5: 5.394912923753372,
  6: 3.187525029320699,
  7: 8.85977748236187,
  8: 2.329594747536338,
  9: 8.700988739009299,
  10: 8.747016726841995,
  11: 9.390676985128962,
  12: 9.979341105333376,
  13: 7.671882889311269,
  14: 4.798756203039089,
  15: 8.736771141863388,
  16: 7.682734138645182,
  17: 4.213570022770702,
  18: 2.3877714576830233,
  19: 3.546221576407765,
  20: 2.963081204559901,
  21: 0.42093189636361883,
  22: 9.877223897360315,
  23: 3.8432664715968166,
  24: 2.1825388786506417,
  25: 7.863450144155521,
  26: 4.175807757849284,
  27: 9.447320222914103,
  28: 6.134113892107077,
  29: 9.911686261369766,
  30: 9.427317741351256,
  31: 6.077367948788591,
  32: 2.3066981171775867,
  33: 2.2048620907017535,
  34: 7.795844735667533,
  35: 0.5784267656339637,
  36: 8.837858849634257,
  37: 9.949078226464353,
  38: 3.9624201890265875,
  39: 6.960206180537922,
  40: 8.158331249906178,
  41: 2.2381761482262306,
  42: 5.929399348417031,
  43: 0.9148683739775487,
  44: 2.6560004258870604,
  45: 8.887480798689772,
  46: 8.621276172654506,
  47: 6.552419806390217,
  48: 0.8698675991141014,
  49: 3.72688517012314,
  50: 7.234201136885849,
  51: 0.8104621590764793,
  52: 6.832587636595959,
  53: 8.512069140487688,
  54: 4.80586577326648,
  55: 8.246809659251491,
  56: 6.780161525590636,
  57: 2.6702827016942132,
  58: 7.974260216069281,
  59: 8.505817290942419,
  60: 7.083629767150348,
  61: 6.974714616692836,
  62: 6.186113782151843,
  63: 1.586051052930737,
  64: 8.71843527745232,
  65: 8.258167505647627,
  66: 3.351188542591419,
  67: 1.607598960483082,
  68: 8.32134177957742,
  69: 0.0638587171683358,
  70: 6.169269183757422,
  71: 6.3181352701666835,
  72: 6.340057030996114,
  73: 7.798453951511436,
  74: 7.61027902502028,
  75: 9.629920038589946,
  76: 6.326218931339481,
  77: 1.0250972799067926,
  78: 6.878857223008134,
  79: 3.0096356694681625,
  80: 0.673506014687717,
  81: 3.4588305695295674,
  82: 0.4574203381251285,
  83: 9.734889691773969,
  84: 7.496518317429247,
  85: 7.582631959290226,
  86: 0.22123551528997254,
  87: 4.886431904046658,
  88: 6.832953766065052,
  89: 2.736266662816659,
  90: 4.261813022359729,
  91: 1.6362382119166918,
  92: 6.936822257814886,
  93: 0.823810456158427,
  94: 6.545112142811353,
  95: 9.508635622504103,
  96: 4.323348010426019,
  97: 4.197273169261223,
  98: 3.9759439796279428,
  99: 9.839776479598282},
 'Height': {0: 5.96269878482053,
  1: 1.205668857772788,
  2: 6.962887758781397,
  3: 7.247667715287615,
  4: 3.152903378306103,
  5: 7.907231648389636,
  6: 6.2589137643700905,
  7: 6.158631881823045,
  8: 0.2440078155653802,
  9: 0.21269410850387138,
  10: 5.28937134027212,
  11: 7.987832357736654,
  12: 3.5071181545171015,
  13: 4.019309136092422,
  14: 6.275054632183701,
  15: 9.840834691992951,
  16: 4.177667821673338,
  17: 7.375823015888915,
  18: 1.1047411313139466,
  19: 2.8723899165408175,
  20: 2.3360775104990994,
  21: 0.1787393473341381,
  22: 4.277731337358624,
  23: 6.796472826930699,
  24: 9.499611839502254,
  25: 0.8941100231225951,
  26: 8.791183075621646,
  27: 4.674015112498697,
  28: 1.6703394609207523,
  29: 2.3167170138344337,
  30: 6.496466489923685,
  31: 5.126885110165086,
  32: 1.7652803200550826,
  33: 1.8643826214425452,
  34: 3.501252591667301,
  35: 9.691026301408113,
  36: 9.27752283195213,
  37: 1.738952492194873,
  38: 7.582384757040913,
  39: 1.5389590633985506,
  40: 2.2444057183666066,
  41: 5.3697442289341355,
  42: 5.8008620783781115,
  43: 8.774608626303804,
  44: 1.2951492128280417,
  45: 9.556514982297534,
  46: 8.09516074724878,
  47: 5.5085737060913935,
  48: 4.084532130706987,
  49: 2.5975378376032623,
  50: 4.9587573507877085,
  51: 2.2018320194981134,
  52: 0.7613085949030018,
  53: 4.951465270139743,
  54: 5.924077846595176,
  55: 3.4780920790219305,
  56: 5.657319639957911,
  57: 8.78629986355158,
  58: 6.584518346584255,
  59: 8.672942009598025,
  60: 8.37013328363672,
  61: 6.801407717603004,
  62: 7.527166395576412,
  63: 8.808707591989284,
  64: 0.29247283034559146,
  65: 1.288698674734452,
  66: 7.435082562916078,
  67: 8.179670241190621,
  68: 5.074677337608362,
  69: 2.870381331749128,
  70: 9.811861780274235,
  71: 2.5980358106415977,
  72: 5.3998537971585545,
  73: 1.069806388269584,
  74: 5.412665786761103,
  75: 3.418721660386861,
  76: 9.320281055100175,
  77: 9.372284872364512,
  78: 0.678370591051719,
  79: 7.081720886452816,
  80: 5.8217046017627325,
  81: 6.209155177674771,
  82: 8.715368061523762,
  83: 9.688778552856915,
  84: 1.3008624013063197,
  85: 0.2458691645880151,
  86: 3.2361021914954122,
  87: 7.704074178077932,
  88: 4.459027063767484,
  89: 9.971245001577111,
  90: 4.513870243296755,
  91: 7.948095487499294,
  92: 2.207696127887604,
  93: 6.804993020747131,
  94: 2.7325952699820935,
  95: 1.5105789178090023,
  96: 9.436159201675988,
  97: 6.385259476640855,
  98: 2.7421520234867005,
  99: 4.09334006315043},
 'Quality': {0: 46.125072415732234,
  1: 52.47791672583277,
  2: 50.54082927823303,
  3: 48.52166767780743,
  4: 42.61420753480399,
  5: 57.732084304809334,
  6: 48.995692976426454,
  7: 43.8924502364153,
  8: 47.355187017545795,
  9: 48.28259505057854,
  10: 56.550757911337485,
  11: 54.67228761122804,
  12: 55.386097872826795,
  13: 40.22062528857295,
  14: 48.323079963595234,
  15: 49.62688303270647,
  16: 40.38384553646113,
  17: 45.19626417490068,
  18: 55.2057964624427,
  19: 42.74219411457998,
  20: 50.70620262905183,
  21: 44.30403744034475,
  22: 40.24241549287787,
  23: 44.82402915199083,
  24: 59.517475098201075,
  25: 56.030742237659794,
  26: 59.19153288642067,
  27: 49.75708087852725,
  28: 42.19472397355007,
  29: 50.95918977947386,
  30: 49.08754669119922,
  31: 56.887141654792316,
  32: 41.96165161568489,
  33: 49.76482274043556,
  34: 43.00097329387968,
  35: 46.4935185378012,
  36: 54.747141547755994,
  37: 49.52036258737533,
  38: 47.51776570291538,
  39: 47.8895255714007,
  40: 49.18893536811973,
  41: 55.700330876741134,
  42: 57.84169377880469,
  43: 59.10669373007856,
  44: 55.7380677251059,
  45: 46.308137914960255,
  46: 53.762694121730846,
  47: 48.75206248110784,
  48: 45.09341244092102,
  49: 56.81743158851845,
  50: 40.7685269792465,
  51: 58.03523984270847,
  52: 49.22954929249468,
  53: 52.74402953616561,
  54: 53.187078444115656,
  55: 57.90235481413073,
  56: 52.733393643344144,
  57: 52.27867169520124,
  58: 41.3330408112138,
  59: 50.368160438904084,
  60: 43.003380016340834,
  61: 54.74867537442971,
  62: 50.24443841625349,
  63: 53.604555584167066,
  64: 40.833458012047686,
  65: 41.69584032091606,
  66: 54.326467761253646,
  67: 41.44168671997347,
  68: 41.42513455530517,
  69: 40.24216950469775,
  70: 59.1300279659896,
  71: 54.75016718918014,
  72: 47.06502817004128,
  73: 45.930711625753105,
  74: 46.99406459491699,
  75: 55.49307062362364,
  76: 53.22741222140829,
  77: 43.703911357349355,
  78: 43.48218670668169,
  79: 41.96791299426795,
  80: 53.206054394026765,
  81: 55.287453244434715,
  82: 45.30092856650008,
  83: 40.41889922061826,
  84: 41.64343334952855,
  85: 59.357200696900605,
  86: 45.908895549548404,
  87: 55.384462956762675,
  88: 52.49327137708528,
  89: 47.63879279305792,
  90: 44.113745243911104,
  91: 42.42772836318813,
  92: 52.30025936077733,
  93: 55.49267561275576,
  94: 52.878085070822614,
  95: 50.606042664983164,
  96: 40.83902446863272,
  97: 59.36977555188768,
  98: 55.97428383309149,
  99: 45.856440734019294},
 'Difference': {0: 0.29875290836568624,
  1: -0.7517910500951843,
  2: -0.4263575962055433,
  3: 1.1484457091967548,
  4: 0.11327041053776446,
  5: -1.4382779783173667,
  6: 0.9192289345752035,
  7: -0.668144085538994,
  8: 1.8732977762175456,
  9: 1.0800480657146485,
  10: -0.4473218956587512,
  11: 1.281016361735113,
  12: 0.0678555105274033,
  13: 0.8527736751222195,
  14: 0.48473281729447476,
  15: -0.8463566549908735,
  16: -0.643549832317462,
  17: 1.0299608175811612,
  18: -0.33477533210654087,
  19: -0.4036484632419967,
  20: -0.955122579349353,
  21: 0.42359906559346105,
  22: 2.062524919243145,
  23: -1.0675329142542729,
  24: 0.02421945667275807,
  25: 1.4122205554154292,
  26: -0.07964139124571515,
  27: 0.4523717962497339,
  28: -1.0623935281468797,
  29: 0.4283070972076486,
  30: -0.18714426500454878,
  31: 0.985729995679863,
  32: 1.1873860515647512,
  33: 2.589563642018614,
  34: 0.5796331732135757,
  35: 0.32579631658216646,
  36: 0.19438430157733602,
  37: -0.35316629281068834,
  38: 0.33848384346169114,
  39: -0.29540141013902943,
  40: 0.1684609762696143,
  41: 1.3175975356079597,
  42: -1.0065425652796411,
  43: 1.1398785611290454,
  44: 1.3171150673398653,
  45: -0.11806852699107874,
  46: -2.1218548990085946,
  47: -0.6078219870944325,
  48: 1.2969945465611092,
  49: -0.022868062298882122,
  50: -0.9993022322949108,
  51: -0.5047749212282174,
  52: 0.840620026504553,
  53: 0.5467335682013793,
  54: -0.23893209916969432,
  55: -0.36682441181468756,
  56: -0.3917581490438219,
  57: -0.9224101844985025,
  58: 1.6153756894694418,
  59: -0.3223204692113399,
  60: 1.2171585208254965,
  61: 1.5213160519224513,
  62: 0.9983108981479604,
  63: -0.4316203127180484,
  64: 0.40373009033660945,
  65: -0.024195606390916165,
  66: -0.9037018607301281,
  67: 0.324359281721603,
  68: -1.1790397911598025,
  69: 1.1876793884615637,
  70: -0.4646172972983931,
  71: 0.2011596558728393,
  72: 0.28328787154614216,
  73: -0.25890497370407733,
  74: 0.5866938014752747,
  75: -0.47490365662252443,
  76: 0.8712972974572442,
  77: -1.3459796802467485,
  78: 0.12637957954641182,
  79: 1.9389289990582848,
  80: -1.0003313246055747,
  81: -0.6777449705248515,
  82: 0.513907849658915,
  83: 0.17958178193959795,
  84: 0.3506300992735592,
  85: 0.4891871301476635,
  86: 0.6347214685617699,
  87: 1.1096998419562232,
  88: 0.40981865692851255,
  89: -0.24125765461854246,
  90: 0.6725737012027313,
  91: 1.8998819348952156,
  92: -0.13263374638257355,
  93: -0.9745293046706415,
  94: 1.1070806692869728,
  95: -0.12038116395359824,
  96: -2.172669546014036,
  97: 0.8474216771504216,
  98: -0.5353281859539227,
  99: -0.09053328230416077}}

In [83]:
df.to_dict(orient="records")

[{'Date': Timestamp('1997-07-05 00:00:00'),
  'price': 7370,
  'Quantity': 41,
  'Width': 0.3700763471549262,
  'Height': 5.96269878482053,
  'Quality': 46.125072415732234,
  'Difference': 0.29875290836568624},
 {'Date': Timestamp('1997-07-06 00:00:00'),
  'price': 960,
  'Quantity': 77,
  'Width': 2.3000883728770303,
  'Height': 1.205668857772788,
  'Quality': 52.47791672583277,
  'Difference': -0.7517910500951843},
 {'Date': Timestamp('1997-07-07 00:00:00'),
  'price': 5490,
  'Quantity': 64,
  'Width': 0.7695320162920916,
  'Height': 6.962887758781397,
  'Quality': 50.54082927823303,
  'Difference': -0.4263575962055433},
 {'Date': Timestamp('1997-07-08 00:00:00'),
  'price': 5291,
  'Quantity': 84,
  'Width': 3.3987496376806616,
  'Height': 7.247667715287615,
  'Quality': 48.52166767780743,
  'Difference': 1.1484457091967548},
 {'Date': Timestamp('1997-07-09 00:00:00'),
  'price': 5834,
  'Quantity': 65,
  'Width': 0.6535634079894237,
  'Height': 3.152903378306103,
  'Quality': 42.61420753480399,
  'Difference': 0.11327041053776446},
 {'Date': Timestamp('1997-07-10 00:00:00'),
  'price': 6365,
  'Quantity': 26,
  'Width': 5.394912923753372,
  'Height': 7.907231648389636,
  'Quality': 57.732084304809334,
  'Difference': -1.4382779783173667},
 {'Date': Timestamp('1997-07-11 00:00:00'),
  'price': 566,
  'Quantity': 47,
  'Width': 3.187525029320699,
  'Height': 6.2589137643700905,
  'Quality': 48.995692976426454,
  'Difference': 0.9192289345752035},
 {'Date': Timestamp('1997-07-12 00:00:00'),
  'price': 4526,
  'Quantity': 33,
  'Width': 8.85977748236187,
  'Height': 6.158631881823045,
  'Quality': 43.8924502364153,
  'Difference': -0.668144085538994},
 {'Date': Timestamp('1997-07-13 00:00:00'),
  'price': 5678,
  'Quantity': 78,
  'Width': 2.329594747536338,
  'Height': 0.2440078155653802,
  'Quality': 47.355187017545795,
  'Difference': 1.8732977762175456},
 {'Date': Timestamp('1997-07-14 00:00:00'),
  'price': 8422,
  'Quantity': 79,
  'Width': 8.700988739009299,
  'Height': 0.21269410850387138,
  'Quality': 48.28259505057854,
  'Difference': 1.0800480657146485},
 {'Date': Timestamp('1997-07-15 00:00:00'),
  'price': 1785,
  'Quantity': 95,
  'Width': 8.747016726841995,
  'Height': 5.28937134027212,
  'Quality': 56.550757911337485,
  'Difference': -0.4473218956587512},
 {'Date': Timestamp('1997-07-16 00:00:00'),
  'price': 869,
  'Quantity': 20,
  'Width': 9.390676985128962,
  'Height': 7.987832357736654,
  'Quality': 54.67228761122804,
  'Difference': 1.281016361735113},
 {'Date': Timestamp('1997-07-17 00:00:00'),
  'price': 7049,
  'Quantity': 25,
  'Width': 9.979341105333376,
  'Height': 3.5071181545171015,
  'Quality': 55.386097872826795,
  'Difference': 0.0678555105274033},
 {'Date': Timestamp('1997-07-18 00:00:00'),
  'price': 2533,
  'Quantity': 82,
  'Width': 7.671882889311269,
  'Height': 4.019309136092422,
  'Quality': 40.22062528857295,
  'Difference': 0.8527736751222195},
 {'Date': Timestamp('1997-07-19 00:00:00'),
  'price': 5411,
  'Quantity': 68,
  'Width': 4.798756203039089,
  'Height': 6.275054632183701,
  'Quality': 48.323079963595234,
  'Difference': 0.48473281729447476},
 {'Date': Timestamp('1997-07-20 00:00:00'),
  'price': 5151,
  'Quantity': 79,
  'Width': 8.736771141863388,
  'Height': 9.840834691992951,
  'Quality': 49.62688303270647,
  'Difference': -0.8463566549908735},
 {'Date': Timestamp('1997-07-21 00:00:00'),
  'price': 6520,
  'Quantity': 89,
  'Width': 7.682734138645182,
  'Height': 4.177667821673338,
  'Quality': 40.38384553646113,
  'Difference': -0.643549832317462},
 {'Date': Timestamp('1997-07-22 00:00:00'),
  'price': 1284,
  'Quantity': 12,
  'Width': 4.213570022770702,
  'Height': 7.375823015888915,
  'Quality': 45.19626417490068,
  'Difference': 1.0299608175811612},
 {'Date': Timestamp('1997-07-23 00:00:00'),
  'price': 4655,
  'Quantity': 29,
  'Width': 2.3877714576830233,
  'Height': 1.1047411313139466,
  'Quality': 55.2057964624427,
  'Difference': -0.33477533210654087},
 {'Date': Timestamp('1997-07-24 00:00:00'),
  'price': 3485,
  'Quantity': 68,
  'Width': 3.546221576407765,
  'Height': 2.8723899165408175,
  'Quality': 42.74219411457998,
  'Difference': -0.4036484632419967},
 {'Date': Timestamp('1997-07-25 00:00:00'),
  'price': 6496,
  'Quantity': 45,
  'Width': 2.963081204559901,
  'Height': 2.3360775104990994,
  'Quality': 50.70620262905183,
  'Difference': -0.955122579349353},
 {'Date': Timestamp('1997-07-26 00:00:00'),
  'price': 8766,
  'Quantity': 28,
  'Width': 0.42093189636361883,
  'Height': 0.1787393473341381,
  'Quality': 44.30403744034475,
  'Difference': 0.42359906559346105},
 {'Date': Timestamp('1997-07-27 00:00:00'),
  'price': 9374,
  'Quantity': 99,
  'Width': 9.877223897360315,
  'Height': 4.277731337358624,
  'Quality': 40.24241549287787,
  'Difference': 2.062524919243145},
 {'Date': Timestamp('1997-07-28 00:00:00'),
  'price': 2658,
  'Quantity': 76,
  'Width': 3.8432664715968166,
  'Height': 6.796472826930699,
  'Quality': 44.82402915199083,
  'Difference': -1.0675329142542729},
 {'Date': Timestamp('1997-07-29 00:00:00'),
  'price': 7949,
  'Quantity': 28,
  'Width': 2.1825388786506417,
  'Height': 9.499611839502254,
  'Quality': 59.517475098201075,
  'Difference': 0.02421945667275807},
 {'Date': Timestamp('1997-07-30 00:00:00'),
  'price': 2147,
  'Quantity': 29,
  'Width': 7.863450144155521,
  'Height': 0.8941100231225951,
  'Quality': 56.030742237659794,
  'Difference': 1.4122205554154292},
 {'Date': Timestamp('1997-07-31 00:00:00'),
  'price': 2847,
  'Quantity': 80,
  'Width': 4.175807757849284,
  'Height': 8.791183075621646,
  'Quality': 59.19153288642067,
  'Difference': -0.07964139124571515},
 {'Date': Timestamp('1997-08-01 00:00:00'),
  'price': 9267,
  'Quantity': 61,
  'Width': 9.447320222914103,
  'Height': 4.674015112498697,
  'Quality': 49.75708087852725,
  'Difference': 0.4523717962497339},
 {'Date': Timestamp('1997-08-02 00:00:00'),
  'price': 289,
  'Quantity': 42,
  'Width': 6.134113892107077,
  'Height': 1.6703394609207523,
  'Quality': 42.19472397355007,
  'Difference': -1.0623935281468797},
 {'Date': Timestamp('1997-08-03 00:00:00'),
  'price': 2834,
  'Quantity': 49,
  'Width': 9.911686261369766,
  'Height': 2.3167170138344337,
  'Quality': 50.95918977947386,
  'Difference': 0.4283070972076486},
 {'Date': Timestamp('1997-08-04 00:00:00'),
  'price': 3105,
  'Quantity': 48,
  'Width': 9.427317741351256,
  'Height': 6.496466489923685,
  'Quality': 49.08754669119922,
  'Difference': -0.18714426500454878},
 {'Date': Timestamp('1997-08-05 00:00:00'),
  'price': 4758,
  'Quantity': 91,
  'Width': 6.077367948788591,
  'Height': 5.126885110165086,
  'Quality': 56.887141654792316,
  'Difference': 0.985729995679863},
 {'Date': Timestamp('1997-08-06 00:00:00'),
  'price': 1999,
  'Quantity': 10,
  'Width': 2.3066981171775867,
  'Height': 1.7652803200550826,
  'Quality': 41.96165161568489,
  'Difference': 1.1873860515647512},
 {'Date': Timestamp('1997-08-07 00:00:00'),
  'price': 7834,
  'Quantity': 20,
  'Width': 2.2048620907017535,
  'Height': 1.8643826214425452,
  'Quality': 49.76482274043556,
  'Difference': 2.589563642018614},
 {'Date': Timestamp('1997-08-08 00:00:00'),
  'price': 1367,
  'Quantity': 66,
  'Width': 7.795844735667533,
  'Height': 3.501252591667301,
  'Quality': 43.00097329387968,
  'Difference': 0.5796331732135757},
 {'Date': Timestamp('1997-08-09 00:00:00'),
  'price': 1628,
  'Quantity': 98,
  'Width': 0.5784267656339637,
  'Height': 9.691026301408113,
  'Quality': 46.4935185378012,
  'Difference': 0.32579631658216646},
 {'Date': Timestamp('1997-08-10 00:00:00'),
  'price': 3656,
  'Quantity': 59,
  'Width': 8.837858849634257,
  'Height': 9.27752283195213,
  'Quality': 54.747141547755994,
  'Difference': 0.19438430157733602},
 {'Date': Timestamp('1997-08-11 00:00:00'),
  'price': 3990,
  'Quantity': 32,
  'Width': 9.949078226464353,
  'Height': 1.738952492194873,
  'Quality': 49.52036258737533,
  'Difference': -0.35316629281068834},
 {'Date': Timestamp('1997-08-12 00:00:00'),
  'price': 8938,
  'Quantity': 40,
  'Width': 3.9624201890265875,
  'Height': 7.582384757040913,
  'Quality': 47.51776570291538,
  'Difference': 0.33848384346169114},
 {'Date': Timestamp('1997-08-13 00:00:00'),
  'price': 5493,
  'Quantity': 51,
  'Width': 6.960206180537922,
  'Height': 1.5389590633985506,
  'Quality': 47.8895255714007,
  'Difference': -0.29540141013902943},
 {'Date': Timestamp('1997-08-14 00:00:00'),
  'price': 8892,
  'Quantity': 16,
  'Width': 8.158331249906178,
  'Height': 2.2444057183666066,
  'Quality': 49.18893536811973,
  'Difference': 0.1684609762696143},
 {'Date': Timestamp('1997-08-15 00:00:00'),
  'price': 8533,
  'Quantity': 25,
  'Width': 2.2381761482262306,
  'Height': 5.3697442289341355,
  'Quality': 55.700330876741134,
  'Difference': 1.3175975356079597},
 {'Date': Timestamp('1997-08-16 00:00:00'),
  'price': 7613,
  'Quantity': 99,
  'Width': 5.929399348417031,
  'Height': 5.8008620783781115,
  'Quality': 57.84169377880469,
  'Difference': -1.0065425652796411},
 {'Date': Timestamp('1997-08-17 00:00:00'),
  'price': 2712,
  'Quantity': 69,
  'Width': 0.9148683739775487,
  'Height': 8.774608626303804,
  'Quality': 59.10669373007856,
  'Difference': 1.1398785611290454},
 {'Date': Timestamp('1997-08-18 00:00:00'),
  'price': 7141,
  'Quantity': 11,
  'Width': 2.6560004258870604,
  'Height': 1.2951492128280417,
  'Quality': 55.7380677251059,
  'Difference': 1.3171150673398653},
 {'Date': Timestamp('1997-08-19 00:00:00'),
  'price': 9655,
  'Quantity': 10,
  'Width': 8.887480798689772,
  'Height': 9.556514982297534,
  'Quality': 46.308137914960255,
  'Difference': -0.11806852699107874},
 {'Date': Timestamp('1997-08-20 00:00:00'),
  'price': 6335,
  'Quantity': 57,
  'Width': 8.621276172654506,
  'Height': 8.09516074724878,
  'Quality': 53.762694121730846,
  'Difference': -2.1218548990085946},
 {'Date': Timestamp('1997-08-21 00:00:00'),
  'price': 5586,
  'Quantity': 21,
  'Width': 6.552419806390217,
  'Height': 5.5085737060913935,
  'Quality': 48.75206248110784,
  'Difference': -0.6078219870944325},
 {'Date': Timestamp('1997-08-22 00:00:00'),
  'price': 7199,
  'Quantity': 78,
  'Width': 0.8698675991141014,
  'Height': 4.084532130706987,
  'Quality': 45.09341244092102,
  'Difference': 1.2969945465611092},
 {'Date': Timestamp('1997-08-23 00:00:00'),
  'price': 9770,
  'Quantity': 46,
  'Width': 3.72688517012314,
  'Height': 2.5975378376032623,
  'Quality': 56.81743158851845,
  'Difference': -0.022868062298882122},
 {'Date': Timestamp('1997-08-24 00:00:00'),
  'price': 875,
  'Quantity': 41,
  'Width': 7.234201136885849,
  'Height': 4.9587573507877085,
  'Quality': 40.7685269792465,
  'Difference': -0.9993022322949108},
 {'Date': Timestamp('1997-08-25 00:00:00'),
  'price': 8326,
  'Quantity': 18,
  'Width': 0.8104621590764793,
  'Height': 2.2018320194981134,
  'Quality': 58.03523984270847,
  'Difference': -0.5047749212282174},
 {'Date': Timestamp('1997-08-26 00:00:00'),
  'price': 3252,
  'Quantity': 28,
  'Width': 6.832587636595959,
  'Height': 0.7613085949030018,
  'Quality': 49.22954929249468,
  'Difference': 0.840620026504553},
 {'Date': Timestamp('1997-08-27 00:00:00'),
  'price': 1685,
  'Quantity': 57,
  'Width': 8.512069140487688,
  'Height': 4.951465270139743,
  'Quality': 52.74402953616561,
  'Difference': 0.5467335682013793},
 {'Date': Timestamp('1997-08-28 00:00:00'),
  'price': 4043,
  'Quantity': 89,
  'Width': 4.80586577326648,
  'Height': 5.924077846595176,
  'Quality': 53.187078444115656,
  'Difference': -0.23893209916969432},
 {'Date': Timestamp('1997-08-29 00:00:00'),
  'price': 7655,
  'Quantity': 12,
  'Width': 8.246809659251491,
  'Height': 3.4780920790219305,
  'Quality': 57.90235481413073,
  'Difference': -0.36682441181468756},
 {'Date': Timestamp('1997-08-30 00:00:00'),
  'price': 3173,
  'Quantity': 29,
  'Width': 6.780161525590636,
  'Height': 5.657319639957911,
  'Quality': 52.733393643344144,
  'Difference': -0.3917581490438219},
 {'Date': Timestamp('1997-08-31 00:00:00'),
  'price': 1121,
  'Quantity': 33,
  'Width': 2.6702827016942132,
  'Height': 8.78629986355158,
  'Quality': 52.27867169520124,
  'Difference': -0.9224101844985025},
 {'Date': Timestamp('1997-09-01 00:00:00'),
  'price': 3943,
  'Quantity': 63,
  'Width': 7.974260216069281,
  'Height': 6.584518346584255,
  'Quality': 41.3330408112138,
  'Difference': 1.6153756894694418},
 {'Date': Timestamp('1997-09-02 00:00:00'),
  'price': 8089,
  'Quantity': 42,
  'Width': 8.505817290942419,
  'Height': 8.672942009598025,
  'Quality': 50.368160438904084,
  'Difference': -0.3223204692113399},
 {'Date': Timestamp('1997-09-03 00:00:00'),
  'price': 9792,
  'Quantity': 33,
  'Width': 7.083629767150348,
  'Height': 8.37013328363672,
  'Quality': 43.003380016340834,
  'Difference': 1.2171585208254965},
 {'Date': Timestamp('1997-09-04 00:00:00'),
  'price': 6973,
  'Quantity': 84,
  'Width': 6.974714616692836,
  'Height': 6.801407717603004,
  'Quality': 54.74867537442971,
  'Difference': 1.5213160519224513},
 {'Date': Timestamp('1997-09-05 00:00:00'),
  'price': 5775,
  'Quantity': 81,
  'Width': 6.186113782151843,
  'Height': 7.527166395576412,
  'Quality': 50.24443841625349,
  'Difference': 0.9983108981479604},
 {'Date': Timestamp('1997-09-06 00:00:00'),
  'price': 261,
  'Quantity': 45,
  'Width': 1.586051052930737,
  'Height': 8.808707591989284,
  'Quality': 53.604555584167066,
  'Difference': -0.4316203127180484},
 {'Date': Timestamp('1997-09-07 00:00:00'),
  'price': 4397,
  'Quantity': 47,
  'Width': 8.71843527745232,
  'Height': 0.29247283034559146,
  'Quality': 40.833458012047686,
  'Difference': 0.40373009033660945},
 {'Date': Timestamp('1997-09-08 00:00:00'),
  'price': 1095,
  'Quantity': 93,
  'Width': 8.258167505647627,
  'Height': 1.288698674734452,
  'Quality': 41.69584032091606,
  'Difference': -0.024195606390916165},
 {'Date': Timestamp('1997-09-09 00:00:00'),
  'price': 7729,
  'Quantity': 98,
  'Width': 3.351188542591419,
  'Height': 7.435082562916078,
  'Quality': 54.326467761253646,
  'Difference': -0.9037018607301281},
 {'Date': Timestamp('1997-09-10 00:00:00'),
  'price': 9567,
  'Quantity': 34,
  'Width': 1.607598960483082,
  'Height': 8.179670241190621,
  'Quality': 41.44168671997347,
  'Difference': 0.324359281721603},
 {'Date': Timestamp('1997-09-11 00:00:00'),
  'price': 1116,
  'Quantity': 27,
  'Width': 8.32134177957742,
  'Height': 5.074677337608362,
  'Quality': 41.42513455530517,
  'Difference': -1.1790397911598025},
 {'Date': Timestamp('1997-09-12 00:00:00'),
  'price': 7969,
  'Quantity': 91,
  'Width': 0.0638587171683358,
  'Height': 2.870381331749128,
  'Quality': 40.24216950469775,
  'Difference': 1.1876793884615637},
 {'Date': Timestamp('1997-09-13 00:00:00'),
  'price': 6539,
  'Quantity': 75,
  'Width': 6.169269183757422,
  'Height': 9.811861780274235,
  'Quality': 59.1300279659896,
  'Difference': -0.4646172972983931},
 {'Date': Timestamp('1997-09-14 00:00:00'),
  'price': 7992,
  'Quantity': 63,
  'Width': 6.3181352701666835,
  'Height': 2.5980358106415977,
  'Quality': 54.75016718918014,
  'Difference': 0.2011596558728393},
 {'Date': Timestamp('1997-09-15 00:00:00'),
  'price': 6963,
  'Quantity': 44,
  'Width': 6.340057030996114,
  'Height': 5.3998537971585545,
  'Quality': 47.06502817004128,
  'Difference': 0.28328787154614216},
 {'Date': Timestamp('1997-09-16 00:00:00'),
  'price': 8016,
  'Quantity': 89,
  'Width': 7.798453951511436,
  'Height': 1.069806388269584,
  'Quality': 45.930711625753105,
  'Difference': -0.25890497370407733},
 {'Date': Timestamp('1997-09-17 00:00:00'),
  'price': 8629,
  'Quantity': 70,
  'Width': 7.61027902502028,
  'Height': 5.412665786761103,
  'Quality': 46.99406459491699,
  'Difference': 0.5866938014752747},
 {'Date': Timestamp('1997-09-18 00:00:00'),
  'price': 978,
  'Quantity': 50,
  'Width': 9.629920038589946,
  'Height': 3.418721660386861,
  'Quality': 55.49307062362364,
  'Difference': -0.47490365662252443},
 {'Date': Timestamp('1997-09-19 00:00:00'),
  'price': 9368,
  'Quantity': 42,
  'Width': 6.326218931339481,
  'Height': 9.320281055100175,
  'Quality': 53.22741222140829,
  'Difference': 0.8712972974572442},
 {'Date': Timestamp('1997-09-20 00:00:00'),
  'price': 4987,
  'Quantity': 77,
  'Width': 1.0250972799067926,
  'Height': 9.372284872364512,
  'Quality': 43.703911357349355,
  'Difference': -1.3459796802467485},
 {'Date': Timestamp('1997-09-21 00:00:00'),
  'price': 4959,
  'Quantity': 42,
  'Width': 6.878857223008134,
  'Height': 0.678370591051719,
  'Quality': 43.48218670668169,
  'Difference': 0.12637957954641182},
 {'Date': Timestamp('1997-09-22 00:00:00'),
  'price': 6431,
  'Quantity': 23,
  'Width': 3.0096356694681625,
  'Height': 7.081720886452816,
  'Quality': 41.96791299426795,
  'Difference': 1.9389289990582848},
 {'Date': Timestamp('1997-09-23 00:00:00'),
  'price': 8671,
  'Quantity': 30,
  'Width': 0.673506014687717,
  'Height': 5.8217046017627325,
  'Quality': 53.206054394026765,
  'Difference': -1.0003313246055747},
 {'Date': Timestamp('1997-09-24 00:00:00'),
  'price': 8784,
  'Quantity': 57,
  'Width': 3.4588305695295674,
  'Height': 6.209155177674771,
  'Quality': 55.287453244434715,
  'Difference': -0.6777449705248515},
 {'Date': Timestamp('1997-09-25 00:00:00'),
  'price': 7308,
  'Quantity': 29,
  'Width': 0.4574203381251285,
  'Height': 8.715368061523762,
  'Quality': 45.30092856650008,
  'Difference': 0.513907849658915},
 {'Date': Timestamp('1997-09-26 00:00:00'),
  'price': 5376,
  'Quantity': 17,
  'Width': 9.734889691773969,
  'Height': 9.688778552856915,
  'Quality': 40.41889922061826,
  'Difference': 0.17958178193959795},
 {'Date': Timestamp('1997-09-27 00:00:00'),
  'price': 2162,
  'Quantity': 16,
  'Width': 7.496518317429247,
  'Height': 1.3008624013063197,
  'Quality': 41.64343334952855,
  'Difference': 0.3506300992735592},
 {'Date': Timestamp('1997-09-28 00:00:00'),
  'price': 164,
  'Quantity': 76,
  'Width': 7.582631959290226,
  'Height': 0.2458691645880151,
  'Quality': 59.357200696900605,
  'Difference': 0.4891871301476635},
 {'Date': Timestamp('1997-09-29 00:00:00'),
  'price': 8106,
  'Quantity': 26,
  'Width': 0.22123551528997254,
  'Height': 3.2361021914954122,
  'Quality': 45.908895549548404,
  'Difference': 0.6347214685617699},
 {'Date': Timestamp('1997-09-30 00:00:00'),
  'price': 2668,
  'Quantity': 42,
  'Width': 4.886431904046658,
  'Height': 7.704074178077932,
  'Quality': 55.384462956762675,
  'Difference': 1.1096998419562232},
 {'Date': Timestamp('1997-10-01 00:00:00'),
  'price': 5563,
  'Quantity': 57,
  'Width': 6.832953766065052,
  'Height': 4.459027063767484,
  'Quality': 52.49327137708528,
  'Difference': 0.40981865692851255},
 {'Date': Timestamp('1997-10-02 00:00:00'),
  'price': 2127,
  'Quantity': 85,
  'Width': 2.736266662816659,
  'Height': 9.971245001577111,
  'Quality': 47.63879279305792,
  'Difference': -0.24125765461854246},
 {'Date': Timestamp('1997-10-03 00:00:00'),
  'price': 2795,
  'Quantity': 68,
  'Width': 4.261813022359729,
  'Height': 4.513870243296755,
  'Quality': 44.113745243911104,
  'Difference': 0.6725737012027313},
 {'Date': Timestamp('1997-10-04 00:00:00'),
  'price': 9787,
  'Quantity': 95,
  'Width': 1.6362382119166918,
  'Height': 7.948095487499294,
  'Quality': 42.42772836318813,
  'Difference': 1.8998819348952156},
 {'Date': Timestamp('1997-10-05 00:00:00'),
  'price': 5358,
  'Quantity': 31,
  'Width': 6.936822257814886,
  'Height': 2.207696127887604,
  'Quality': 52.30025936077733,
  'Difference': -0.13263374638257355},
 {'Date': Timestamp('1997-10-06 00:00:00'),
  'price': 5718,
  'Quantity': 39,
  'Width': 0.823810456158427,
  'Height': 6.804993020747131,
  'Quality': 55.49267561275576,
  'Difference': -0.9745293046706415},
 {'Date': Timestamp('1997-10-07 00:00:00'),
  'price': 6836,
  'Quantity': 47,
  'Width': 6.545112142811353,
  'Height': 2.7325952699820935,
  'Quality': 52.878085070822614,
  'Difference': 1.1070806692869728},